inherit_from: .rubocop_todo.yml

AllCops:
  # Exclude:
  # TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false

Metrics/MethodLength:
  Max: 1000

Metrics/ModuleLength:
  Max: 1000

Layout/LineLength:
  Max: 5000

Metrics/ClassLength:
  Max: 2000

Metrics/AbcSize:
  Max: 200

Metrics/BlockLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 30

Style/NumericLiteralPrefix:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ParameterLists:
  Max: 20

Style/RaiseArgs:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/HashLikeCase:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/FloatComparison:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false